#!/bin/bash
#
# This script will setup the boot loader correctly
#

################################################## 
# Sets up the boot loader 
# Globals:
#   CHROOT_DIR
# Arguments
#   install_disk
# Returns:
#   None
##################################################
function bootloader_setup {
  local install_disk=$1

  # Initilize the progress bar
  progress_bar_init $BASH_SOURCE $FUNCNAME  

  # Mounts
  run_command "mount --bind /dev/ ${CHROOT_DIR}/dev"
  run_chroot_command ${CHROOT_DIR} "mount -t proc none /proc"
  run_chroot_command ${CHROOT_DIR} "mount -t sysfs none /sys"
  run_chroot_command ${CHROOT_DIR} "mount -t devpts none /dev/pts"

  # Copy the background from the install
  run_command "cp /lib/live/mount/medium/isolinux/*.png ${CHROOT_DIR}/boot/grub/." 

  # Install Grub
  run_chroot_command ${CHROOT_DIR} "grub-install ${install_disk}" "Installing grub to ${install_disk}"

  # Update Grub
  run_chroot_command ${CHROOT_DIR} "update-grub2" "Updating boot options"

}

